/**
 *
 * $Id$
 */
package com.cisco.yangide.ext.model.validation;

import com.cisco.yangide.ext.model.Grouping;

/**
 * A sample validator interface for {@link com.cisco.yangide.ext.model.Uses}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UsesValidator {
    boolean validate();

    boolean validateGrouping(Grouping value);
    boolean validateQName(String value);
}
